
package WSHandler;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://WS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param code
     * @return
     *     returns WSHandler.Account
     */
    @WebMethod(operationName = "GetAccountWS")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetAccountWS", targetNamespace = "http://WS/", className = "WSHandler.GetAccountWS")
    @ResponseWrapper(localName = "GetAccountWSResponse", targetNamespace = "http://WS/", className = "WSHandler.GetAccountWSResponse")
    @Action(input = "http://WS/BankService/GetAccountWSRequest", output = "http://WS/BankService/GetAccountWSResponse")
    public Account getAccountWS(
        @WebParam(name = "Code", targetNamespace = "")
        int code);

    /**
     * 
     * @param amount
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Converter")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Converter", targetNamespace = "http://WS/", className = "WSHandler.Converter")
    @ResponseWrapper(localName = "ConverterResponse", targetNamespace = "http://WS/", className = "WSHandler.ConverterResponse")
    @Action(input = "http://WS/BankService/ConverterRequest", output = "http://WS/BankService/ConverterResponse")
    public double converter(
        @WebParam(name = "Amount", targetNamespace = "")
        double amount);

    /**
     * 
     * @return
     *     returns java.util.List<WSHandler.Account>
     */
    @WebMethod(operationName = "GetAccountsList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetAccountsList", targetNamespace = "http://WS/", className = "WSHandler.GetAccountsList")
    @ResponseWrapper(localName = "GetAccountsListResponse", targetNamespace = "http://WS/", className = "WSHandler.GetAccountsListResponse")
    @Action(input = "http://WS/BankService/GetAccountsListRequest", output = "http://WS/BankService/GetAccountsListResponse")
    public List<Account> getAccountsList();

}
